import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Box from '../components/ui/Box/Box';
import Button from '../components/ui/Button/Button';

const Home: NextPage = () => {
  return (
    <div className="p-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <h1 className="font-black text-primary">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="">
          Get started by editing <code className="">pages/index.tsx</code>
        </p>

        <div className="">
          <a href="https://nextjs.org/docs" className="">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className=""
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className=""
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </Box>

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <div className="flex items-center justify-center pt-10">
        <Button>Explore App</Button>
      </div>
      <div className="flex items-center justify-center pt-10">
        <Button buttonType="SECONDARY">Watch Demo</Button>
      </div>
      <div className="flex items-center justify-center pt-10">
        <Button buttonType="BLACK" buttonSize="sm">
          Go to App
        </Button>
      </div>
    </div>
  );
};

export default Home;
